---
title: "Results"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, dpi = 400, 
                      fig.path = "figures/", error = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(tsDyn)
library(patchwork)
source("codes/utils.R")
source("codes/dgp_functions.R")
load("data/estimated_rank.RData")
```

```{r}
estimated_rank_df %>% 
  filter(nominal_size == .05) %>% 
  filter(n == 3 & r == 0) %>% 
  count(t, estimated_r, name = "p") %>% 
  group_by(t) %>% 
  mutate(p = p / sum(p)) %>% 
  ggplot(aes(t, estimated_r, fill = p)) + 
  geom_tile(color = "black") + 
  geom_text(aes(label = scales::percent(p)))
```

Reject rate!

```{r}
estimated_rank_df %>% 
  filter(r == 0) %>% 
  count(n, nominal_size, t, estimated_r, name = "estim_count") %>% 
  crossing(r = 0:3) %>% 
  filter(n > r & estimated_r > r) %>% 
  group_by(n, nominal_size, t, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  arrange(desc(nominal_size)) %>% # wider in same order as in the paper
  pivot_wider(names_from = nominal_size, names_prefix = "Nominal size = ", values_fill = 0) %>% 
  select(n, t, r, everything()) %>% 
  arrange(n, t, -r) %>% 
  mutate_at(-(1:3), ~ scales::percent(., accuracy = .01)) %>% 
  knitr::kable(caption = "podivinszky_tbl1", align = rep("c", 10))
```

```{r}
estimated_rank_df %>% 
  filter(t %in% c(50, 100) & nominal_size == .05) %>%
  rename(true_r = r) %>% 
  crossing(r = 0:2) %>% 
  filter(n > r & estimated_r > r) %>% 
  count(n, true_r, t, r, estimated_r, name = "estim_count") %>% 
  group_by(n, true_r, t, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  pivot_wider(names_from = t, values_from = value, names_prefix = "T = ", values_fill = 0) %>% 
  mutate(across(starts_with("T "), scales::percent, accuracy = .01)) %>% 
  arrange(n, true_r, -r) %>% 
  knitr::kable(align = rep("c", 10), caption = "podivinszky_tbl2 2 és 3 idősoron futók csak")

```

# Podivinszky dgp

```{r}
load("data/podivinszky_estimate.RData")
```

## Figure for DGPs

```{r fig.height=8}
set.seed(1)

(podivinszky_dgp(rho = 0, theta = 0) %>% 
    ts() %>% 
    autoplot() + ggtitle("rho = 0, theta = 0")) /
  (podivinszky_dgp(rho = 1, theta = 1) %>% 
     ts() %>% 
     autoplot() + ggtitle("rho = 1, theta = 1") )/
  (podivinszky_dgp(rho = 0, theta = 1) %>% 
     ts() %>% 
     autoplot() + ggtitle("rho = 0, theta = 1"))
```



## Reproduce table 2

### Test on 3 variables

```{r}
podivinszky_estimate_df %>% 
  count(t, rho, theta, xyz_r, name = "estim_count") %>% 
  crossing(r = 0:2) %>% 
  filter(xyz_r > r) %>% 
  group_by(t, rho, theta, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  pivot_wider(names_from = t, names_prefix = "T = ") %>% 
  arrange(rho, theta, -r) %>% 
  knitr::kable(caption = "Podivinszky tbl2 - reject rates", align = rep("c", 6))

```

### Test on 2 variables (x, y)

```{r}
podivinszky_estimate_df %>% 
  count(t, rho, theta, xy_r, name = "estim_count") %>% 
  crossing(r = 0:1) %>% 
  filter(xy_r > r) %>% 
  group_by(t, rho, theta, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  pivot_wider(names_from = t, names_prefix = "T = ") %>% 
  arrange(rho, theta, -r) %>% 
  knitr::kable(caption = "Podivinszky tbl2 - reject rates", align = rep("c", 6))
```

# Podivinszky no wp

```{r}
load("data/podivinszky_no_wp_estimate.RData")
```


## Reproduce table 2

### Test on 3 variables

```{r}
podivinszky_no_wp_estimate %>% 
  filter(t %in% c(50, 100)) %>% 
  count(t, rho, theta, xyz_r, name = "estim_count") %>% 
  crossing(r = 0:2) %>% 
  filter(xyz_r > r) %>% 
  group_by(t, rho, theta, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  pivot_wider(names_from = t, names_prefix = "T = ") %>% 
  arrange(rho, theta, -r) %>% 
  mutate(r = str_c("<=", r)) %>% 
  knitr::kable(caption = "Podivinszky tbl2 - reject rates", align = rep("c", 6))

```

### Test on 2 variables (x, y)

```{r}
podivinszky_no_wp_estimate %>% 
  filter(t %in% c(50, 100)) %>% 
  count(t, rho, theta, xy_r, name = "estim_count") %>% 
  crossing(r = 0:1) %>% 
  filter(xy_r > r) %>% 
  group_by(t, rho, theta, r) %>% 
  summarise(value = sum(estim_count) / 2000) %>% 
  pivot_wider(names_from = t, names_prefix = "T = ") %>% 
  arrange(rho, theta, -r) %>% 
  mutate(r = str_c("<=", r)) %>% 
  knitr::kable(caption = "Podivinszky tbl2 - reject rates", align = rep("c", 6))
```

```{r}
podivinszky_no_wp_estimate %>% 
  count(t, rho, theta, xy_r) %>% 
  group_by(t, rho, theta) %>% 
  mutate(p = n / sum(n)) %>% 
  ggplot(aes(t, p, fill = as.factor(xy_r))) + 
  geom_area(color = "black") + 
  facet_wrap(vars(rho, theta), ncol = 1)
```

```{r}
podivinszky_no_wp_estimate %>% 
  count(t, rho, theta, xyz_r) %>% 
  group_by(t, rho, theta) %>% 
  mutate(p = n / sum(n)) %>% 
  ggplot(aes(t, p, fill = as.factor(xyz_r))) + 
  geom_area(color = "black") + 
  facet_wrap(vars(rho, theta), ncol = 1)
```

# Yield data

```{r}
load("data/yield_df.RData")
```

```{r}
yield_df %>% 
  pivot_longer(-1, names_to = "maturity") %>% 
  na.omit() %>% 
  group_by(maturity) %>% 
  summarise(interval = str_c(min(time), " - ", max(time)), n = n()) %>% 
  knitr::kable()
```


